# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_login_screen(object):
    def x(self):
        message_4=QtWidgets.QMessageBox.question(login_screen,"Icom","هل تريد الخروج ؟")
        if message_4==QtWidgets.QMessageBox.Yes:
                exit()
        else:
                pass
    def login(self):
        try:
                connect_db=mysql.connector.connect(
                        host="localhost",
                        user="root",
                        passwd="",
                        database="Icom_server"

                )
                c1=connect_db.cursor()
                #c1.execute("CREATE DATABASE Icom_server DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci")
                c1.execute("CREATE TABLE if not exists users(name VARCHAR(50),password VARCHAR(90),id int primary key,company_name VARCHAR(50))")
                self.name=self.lineEdit.text()
                self.password=self.lineEdit_2.text()
                c1.execute("select * from users")
                for data in c1:
                        if data[0]==self.name and data[1]==self.password:
                                break
                                
                        else:
                                message=QtWidgets.QMessageBox.warning(login_screen,"Icom","هناك شئ خطأ اعد كتابه بياناتك")
                                continue

        except mysql.connector.Error as erorr1:
                message_2=QtWidgets.QMessageBox.warning(login_screen,"Icom","حدث خطأ في السيرفر")
                message_3=QtWidgets.QMessageBox.warning(login_screen,"Icom",erorr1)
    def setupUi(self, login_screen):
        login_screen.setObjectName("login_screen")
        login_screen.resize(1366, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons\\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login_screen.setWindowIcon(icon)
        login_screen.setStyleSheet(".QMainWindow{\n"
"    background-color:#A8D0B6;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(login_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 110, 581, 391))
        self.label_2.setStyleSheet(".QLabel{\n"
"    border:1px solid rgb(193, 238, 209);\n"
"    background-color:rgb(193, 238, 209);\n"
"    opacity:1;\n"
"    border-radius:10px;\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 160, 111, 31))
        self.label.setStyleSheet(".QLabel{\n"
"    font-size:20px;\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(740, 260, 191, 21))
        self.lineEdit.setStyleSheet(".QLineEdit{\n"
"    background-color:rgb(193, 238, 209);\n"
"    border:1px solid rgb(166, 166, 166);\n"
"    border-radius:10px;\n"
"    font-size:15px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(740, 320, 191, 21))
        self.lineEdit_2.setStyleSheet(".QLineEdit{\n"
"    background-color:rgb(193, 238, 209);\n"
"    border:1px solid rgb(166, 166, 166);\n"
"    border-radius:10px;\n"
"    font-size:15px;\n"
"}")
        self.lineEdit_2.setMaxLength(32766)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.login)
        self.pushButton.setGeometry(QtCore.QRect(630, 390, 161, 31))
        self.pushButton.setStyleSheet(".QPushButton{\n"
"    background-color:rgb(0, 0, 255);\n"
"    color:#fff;\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"}\n"
".QPushButton:hover{\n"
"    background-color:rgb(0, 0, 154);\n"
"    color:#fff;\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.x)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 440, 161, 31))
        self.pushButton_2.setStyleSheet(".QPushButton{\n"
"    background-color:rgb(255, 0, 4);\n"
"    color:#fff;\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"}\n"
".QPushButton:hover{\n"
"    background-color:#A20000;\n"
"    color:#fff;\n"
"    border-radius:10px;\n"
"    font-size:14px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 240, 91, 20))
        self.label_3.setStyleSheet(".QLabel{\n"
"    font-size:13px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(840, 300, 91, 20))
        self.label_4.setStyleSheet(".QLabel{\n"
"    font-size:13px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 240, 141, 121))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("icons\\icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        login_screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        login_screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_screen)
        self.statusbar.setObjectName("statusbar")
        login_screen.setStatusBar(self.statusbar)

        self.retranslateUi(login_screen)
        QtCore.QMetaObject.connectSlotsByName(login_screen)

    def retranslateUi(self, login_screen):
        _translate = QtCore.QCoreApplication.translate
        login_screen.setWindowTitle(_translate("login_screen", "Icom v-1.0"))
        self.label.setText(_translate("login_screen", "تسجيل دخول"))
        self.lineEdit.setPlaceholderText(_translate("login_screen", "ادخل اسم المستخدم"))
        self.lineEdit_2.setPlaceholderText(_translate("login_screen", "ادخل كلمه المرور"))
        self.pushButton.setText(_translate("login_screen", "تسجيل دخول"))
        self.pushButton_2.setText(_translate("login_screen", "خروج"))
        self.label_3.setText(_translate("login_screen", "اسم المستخدم"))
        self.label_4.setText(_translate("login_screen", "كلمه المرور"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_screen = QtWidgets.QMainWindow()
    ui = Ui_login_screen()
    ui.setupUi(login_screen)
    login_screen.showMaximized()
    sys.exit(app.exec_())
